name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project’s Python version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install other dependencies
          pip install pytest pytest-cov  # Install pytest and pytest-cov for coverage
      - name: Install NLTK data
        run: |
          python -c "import nltk; nltk.download('vader_lexicon')"
          python -c "import nltk; nltk.download('punkt')"
          python -c "import nltk; nltk.download('stopwords')"
          python -c "import nltk; nltk.download('wordnet')"
      - name: Run Tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings --cov=financial_analysis
