name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project’s Python version
      - name: Install TA-Lib Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc wget
          sudo apt-get install -y python3-dev  # Add python3-dev to ensure proper building
          sudo apt-get install -y libta-lib0 libta-lib-dev  # Ensure TA-Lib libraries are installed

      - name: Install TA-Lib from Source (if needed)
        run: |
          if [ ! -d "/usr/local/lib/libta-lib.a" ]; then
            echo "Installing TA-Lib from source..."
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib/
            ./configure --prefix=/usr/local
            make
            sudo make install
            sudo ldconfig  # Reload library paths
          else
            echo "TA-Lib is already installed."
          fi

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install other dependencies
          pip install pytest pytest-cov  # Install pytest and pytest-cov for coverage
      - name: Install NLTK data
        run: |
          python -c "import nltk; nltk.download('vader_lexicon')"
          python -c "import nltk; nltk.download('punkt')"
          python -c "import nltk; nltk.download('stopwords')"
          python -c "import nltk; nltk.download('wordnet')"
      - name: Run Tests
        run: |
          pytest tests/ 
