name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install System Dependencies for TA-Lib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc wget
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libta-lib0 libta-lib-dev  # Install TA-Lib system dependencies

      - name: Install TA-Lib Python Package
        run: |
          pip install ta-lib  # Install the Python package for TA-Lib

      - name: Install Other Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install other dependencies
          pip install pytest pytest-cov  # Install pytest for testing

      - name: Install NLTK Data (If Used)
        run: |
          python -c "import nltk; nltk.download('vader_lexicon')"
          python -c "import nltk; nltk.download('punkt')"
          python -c "import nltk; nltk.download('stopwords')"
          python -c "import nltk; nltk.download('wordnet')"

      - name: Run Tests
        run: |
          pytest tests/
